# Generated by Django 4.1.4 on 2022-12-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schema",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
