# Generated by Django 4.1.4 on 2022-12-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schemas", "0003_column_max_int_column_min_int"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schema",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
